### ISSUE TITLE
Adding a button  in the GUI that redirects to the documentation website 

### ISSUE THREAD

**Issue by leilaicruz** [SATAY-LL/Transposonmapper#45]
**Is your feature request related to a problem? Please describe.**
I would like to redirect the HELP of the GUI to a nice layout pointing to the documentation of the pipeline in the jupyter book: 
https://satay-ll.github.io/SATAY-jupyter-book/01-bash-GUI/processing_workflow.html

**Describe the solution you'd like**
A button saying `Click here to see the GUI documentation` and go to the web-page using Chrome as browser (or other one). I have tried with Chrome only. With Chrome I would like to automatize the manual tweak of making Chrome to run without a sandbox with a root user . I have tried this [trick](https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-run-google-chrome-as-root-fedora-16-centos-6-rhel-6.html) using the `sed` command as [HERE](https://unix.stackexchange.com/questions/20573/sed-insert-text-after-the-last-line) in the dockerfile but **it did not work**. 

**Describe alternatives you've considered**
 This seems more complicated than I thought. I have managed to have it working if I do **manual tweaking** in the container terminal , but this is not reliable for users to do it. 

These are the steps: 

I did install : 
-  chrome in the dockerfile 
```
# Install Google Chrome
RUN apt-get install wget
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install ./google-chrome*.deb --yes

# # Making chrome the default browser
RUN xdg-settings set default-web-browser google-chrome.desktop


# Installing nano  as bash editor
RUN apt-get -y install nano
```

After build the image , then :

1. Run the container in bash mode : 

`docker run --rm -it --net=host -e DISPLAY=:0 -v $(pwd):/data USERNAME/satay bash`

2. Open the google chrome config file in the nano editor in the terminal of the container

`nano ../usr/bin/google-chrome`

**Steps inside nano:**

  1. Add `–no-sandbox` at the end of the last line (Line No: 49) of the file.
      - That is from `exec -a "$0" "$HERE/chrome" "$@"` go to `exec -a "$0" "$HERE/chrome" "$@" --no-sandbox`
  
  3. Save and exit 
  
      - Ctrl-O 
      - Ctrl-X

4. Run the pipeline by writing the following command: 

`bash ../opt/satay/satay.sh` 

**Additional context**
- The error I get after clicking the button with the following code: `xdg-open https://satay-ll.github.io/SATAY-jupyter-book/Introduction.html` and without the manual tweak . 
![image](https://user-images.githubusercontent.com/11459658/128034344-e8a0ddc8-ab39-42ed-a731-2e5a1b3ab445.png)

- When attempting to automatize the manual tweak by adding the `sed` command to the dockerfile or in the terminal :
`sed -i -e '48aexec -a "$0" "$HERE/chrome" "$@" --no-sandbox' ../usr/bin/google-chrome`

and deleting last line from the google-chrome file : `sed -i '$ d' ../usr/bin/google-chrome` 

I get the following error: 
![image](https://user-images.githubusercontent.com/11459658/128035820-99d74749-9045-491b-a183-a5742caf8b3f.png)

And my `/usr/bin/google-chrome file` looks like how it should , after this: 
![image](https://user-images.githubusercontent.com/11459658/128036076-09e9d66e-2c3a-45e0-8380-e427f39ba66b.png)

What I am doing wrong??

**Comment by mwakok** [comment]
I had a look, but I haven't been able to get to a fully working solution. I can't find what you are doing wrong by adding the command to the Dockerfile to update the google-chrome file. Also, it seems that the `--no-sandbox` option is not a very secure method.

To circumvent the issue with Chrome not running as root (so we don't need to add `--no-sandbox`), we can add a new user to in the Dockerfile:

```
RUN groupadd -g 1000 developer && \
    useradd -d /home/developer -s /bin/bash -m developer -u 1000 -g 1000 &&\
    chown developer:developer /home/developer

USER developer
ENV HOME /home/developer
```
These commands need to be added after all installation commands in the Dockerfile. Furthermore, we then need to add the flag `--privileged` to the `docker run` command. 

These settings get chrome running in the Docker container. However, on my system not all pages can be loaded due to gpu related issues and the experience is slow and buggy. Similarly, I tried to work with Firefox, but is unbearingly slow through X11.

We could also opt for an alternative strategy, by providing the documentation as pdf's in the docker image. This has the advantage that no internet connection (and browser) is needed to access the files. We can for example easily export the jupyter book to a pdf: https://jupyterbook.org/advanced/pdf.html and use a pdf view such as [evince](https://help.ubuntu.com/community/Evince) to view the files. This could also be a better solution to display the help.md file.

**Comment by leilaicruz** [comment]
Yes a quick alternative I found was to add a button in the GUI to point to the help.md of the GUI as a plain text.

what do propose could be better , but we need to install the required programs to display the pdf , and to convert the help.md into a pdf document which is straightforward , and store it in the docker image .

**Comment by mwakok** [comment]
It seems that the terminator, the terminal/editor I picked to display the adapters file, is no longer supported. I exchanged it with gedit. 

I also ran into some issues with the pdf viewer `atril` and replaced it with `evince`.

Let me know if it all works.

**Comment by leilaicruz** [comment]
yes now it works
