### ISSUE TITLE
Post processing functions require pysam

### ISSUE THREAD

**Issue by T-Wisse** [SATAY-LL/Transposonmapper#64]
**Describe the bug**
Running tutorial functions from [here](https://satay-ll.github.io/Transposonmapper/06-Tutorials/tutorial.html) on my windows laptop results in an error: ModuleNotFoundError: No module named 'pysam'. This is at least the case for cells "Zoom in into the chromosomes" and "Getting the volcano plot". I have installed the transponmapper package using `pip install transposonmapper`.  This indeed does not install pysam, but these functions should run without it.

**To Reproduce**
1. Download the .ipynb file from the link above
2. Open the file in visual studio code
3. Run the cell

**Screenshots**
![image](https://user-images.githubusercontent.com/70693768/142839738-eaea9e7e-8362-47df-99af-d28499b74c51.png)
Error from running the volcano plot cell

**Comment by leilaicruz** [comment]
Yes indeed, the issue may happen because of the _init_.py file that calls the transposonmapper package (necessary for how the tests are currently set up) is triggering the import of the pysam module that is you are a Windows user or Mac you wont have it indeed. This package is necessary for the reading of the bamfile in the transposon sequencing analysis. 
This was intended to be only part of the docker image , so other OS can run it as well , which is the case , but we thought that the post processing part could be run independently of that , but it seems is not. 

Here I will post some solutions to this problem that you could implement :
- **(recommended)** Install a VMware , in order to have a Linux environment in your Windows machine and that then you can install without problem all the linux dependent packages and run the post-processing analysis . You can find the VMware application for Wndows here: https://www.vmware.com/go/getplayer-win
- **(not recommended)** Make a fork of the repo, DONT INSTALL THE PACKAGE and take the functions from the module you need (module statistics if you want to run volcano plots ) and run it separately as you want . This solution involved a bit of tinkering so you can use the functions you need detached from the package , but it is not ideal , because you will use it how is not intended to be. Yet, it should render the same result. 

We are going to see if we can find a workaround on that , once we find it we will post it here. 
Thanks for your contributions!

**Comment by mwakok** [comment]
An easy work-around would be to move the `import pysam` call inside the script `transposonmapper.py` to the actual function `transposonmapper`. I think you are right that the `__init__.py` file is importing transposonmapper and executing the import calls present outside the function. You would need to remove line 22 and replace line 115 with:

```python
try:
    import pysam
except ImportError:
    print("Failed to import pysam")
    sys.exit(1)

bam = pysam.AlignmentFile(bamfile, "rb")
```

Don't forget to `import sys` in the script though.

I also tried to execute the tutorial notebook and am (after fixing the pysam error) now encountering a data improt problem. It seems that no files with the extension `.sorted.bam.wig` or `.sorted.bam.bed` are present in the package. Also, to make the code a bit cleaner, you could replace the double for-loop for importing the data with something like:

```python
import glob
data_dir = pkg_resources.resource_filename("transposonmapper", "data_files/files4test/")
wig_files = glob.glob(os.path.join(data_dir, '*sorted.bam.wig'))
bed_files = glob.glob(os.path.join(data_dir, '*sorted.bam.bed'))
```

**Comment by leilaicruz** [comment]
Thanks @mwakok  !! That indeed make sense to put the unwanted default libraries into the function , so the init file does not trigger its execution. 
Did you try it and did not give you the pysam error anymore right? 
So then I would implement it and make a new release after that bug fix. 
thanks!

**Comment by leilaicruz** [comment]
Great!  I did this PR: https://github.com/SATAY-LL/Transposonmapper/pull/65 and put you as reviewer for you to try it out , and see if everything works fine now , thanks

**Comment by leilaicruz** [comment]
We found a workaround that will be converted into a new release of the transposonmapper python package (from version 1.1.2  to version 1.1.3). Please install again [transposonmapper from Pypi ](https://pypi.org/project/transposonmapper/)and hope everything works for you now.

**Comment by T-Wisse** [comment]
This indeed fixed my issue. Thank you.
